### PR TITLE
Feat: Vue 3

### LINKED ISSUE #24: index.js:239 Uncaught TypeError: Cannot set property '$illusory' of undefined
i use vue 3 + vite + composition API.

after run npm i v-shared-element then use v shared on my vue app, i found this error

index.js:239 Uncaught TypeError: Cannot set property '$illusory' of undefined

### LINKED ISSUE #25: Vue3??
Does it works with vue3 ? 
I have an error that seems to be related with Vue3!

### PR DESCRIPTION
**Pull request by domgew**
Closes #25 
Closes #24

### CODE REVIEW

**Comment by justintaddei** [comment]
At work. I will review soon.

**Comment by justintaddei** [comment]
Look great! I would, however, love to maintain backward compatibility with Vue2 if it's possible.  I wasn't sure how to write this in a backward-compatible way myself, which is why I haven't worked on this yet. Do you think it's possible to implement it in such a way that it can support both Vue2 and Vue3? If not, we can just move forward from here and maintain a separate branch for Vue2 support as long as needed.

Thank you for work on this!

**Comment by domgew** [comment]
Unfortunately I don't think this is possible at the moment. Otherwise big libraries probably would not have a separate branch/tag for Vue 3 (@next).
But there is a [migration build](https://v3.vuejs.org/guide/migration/migration-build.html#overview) of Vue which might be worth a look. Nuxt however is on the limitations list.

**Comment by domgew** [comment]
@justintaddei 
I have created a [backwards compatible version](https://github.com/domgew/v-shared-element/tree/vue3-vue2) which seems to work with Vue 2 and Vue 3 but the code is less elegant and the package.json is not a clean as one might wish. Nevertheless, let me know whether you want to go with this approach then I'll merge the compatibility into this pull request. The other way would be to have a separate branch for Vue 3 (e.g. `next`) or make a breaking version change and not support Vue 2 with future updates.

**Comment by justintaddei** [comment]
Definitely like this approach better than splitting the repo. It looks great to me but I've only been able to view this on my phone. I'll take a more in-depth look later today just to double check. When you can, please merge this into the PR!

**Comment by domgew** [comment]
I've merged the Vue 2 compatible version and also taken the liberty to update the documentation (README.md and CHANGELOG.md). The latter under the assumption that it'll be merged tomorrow (July 5th). Furthermore, I've decreased the version number to 3.1.0 as there is no breaking change anymore.

**Review by justintaddei — APPROVED** [review]
Everything looks good! I reverted the version number to 3.0.3 because it will be bumped and tagged automatically when I publish the update.

I also credited you for Vue 3 support in the README. Let me know if that is okay. I'll wait to publish until I hear from you.

**Comment by domgew** [comment]
I don't mind and I'm looking forward to using the official package instead of a git ref for my Vue 3 projects.

**Comment by justintaddei** [comment]
> I'm looking forward to using the official package instead of a git ref for my Vue 3 projects.

Thank you for all of your work on this!  

v3.1.0 has just been [published on npm](https://www.npmjs.com/package/v-shared-element/v/3.1.0).

**Pull request merged**
